create a new page/new-project with submit and home button
AndryBasaraba/Andrii-PM pull request #7
Opened 2023-08-10 09:20 UTC by AndryBasaraba

2023-08-10 10:23 UTC, Kheirah requested changes
Nice, but there's still quite a bit left to do.

One major change revolves around the use of raw css. Use `styled-components` instead.
Another rather small change is the submit event which needs to be catched by the form instead of triggered by the button.

2023-08-10 10:23 UTC, Kheirah commented on components/TaskCard/Card.module.css
`styled-components` instead of CSS.

2023-08-10 10:23 UTC, Kheirah commented on components/Form/index.js
> +      );
This is something you could best put in a separate `useEffect` which reacts to a change in `projectData`.
After you call `setProjectData` the `useEffect` will notice that the state changed and run its callback.
```js
useEffect(() => {
    localStorage.setItem(
        "projectsData",
        JSON.stringify([...projectsData, newProject])
    );
}, [projectData]);
```

2023-08-10 10:23 UTC, Kheirah commented on components/Form/index.js
> +          onClick={formSubmitHandler}
The submit event is not triggered by the `onClick` of the submit button **but by the form.**
Add the `onSubmit` event to the form and move the `formSubmitHandler` up to the form.

2023-08-10 10:23 UTC, Kheirah commented on components/Form/index.js
> +      newErrors.dueBy = "Due by must be a valid future date";
```suggestion
      newErrors.dueBy = "Pick a valid future date";
```

2023-08-14 12:21 UTC, AndryBasaraba commented
all comments have been corrected

2023-08-14 12:21 UTC, merged

2023-08-16 09:58 UTC, Kheirah commented on components/Form/index.js
> +      );
From the perspective of React `localStorage` is an external system. `localStorage` not part of React but of the browser. _Whenever you want to synchronize your app's state with an external system, you use `useEffect`._

In your case, you manage project data (your state) which you want to save to `localStorage` (the browser). Saving to the browser's `localStorage` is a considered a side-effect. You can [read more here](https://react.dev/learn/synchronizing-with-effects).